version: "3.8"
services:
  oracle:
    image: gvenzl/oracle-free:slim
    container_name: oracle-free
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: "YourStrongPass123!"
      APP_USER: "devuser"
      APP_USER_PASSWORD: "devpass123!"
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle-data:
